
#create a hash.  add one key value pair in the hash the key should be :random_numbers the value should be 5 randomly generated integers between 12 and 21 inclusive. 
hasha = {}
hasha[:random_numbers] = [rand(12..21), rand(12..21), rand(12..21), rand(12..21), rand(12..21)]

#create a second hash the key :user_input the values should be 5 positive integers that the program recieves as input also between 12 and 21 also inclusive
puts "Please provide 5 integer values between 12 and 21, both inclusive:"
puts "What is number 1?"
num1 = gets.chomp.to_i
puts "What is number 2?"
num2 = gets.chomp.to_i
puts "What is number 3?"
num3 = gets.chomp.to_i
puts "What is number 4?"
num4 = gets.chomp.to_i
puts "What is number 5?"
num5 = gets.chomp.to_i
hashb = {}

hasha[:user_input] = [num1, num2, num3, num4, num5]



#create a second hash, the keys in this are has the numbers either entered by the user or rand. generated.

hash_totals = {}

#all of the keys should be the numbers generated or input.
#the value of they keys should be the count of times the # was generated randomly & the count of times that the # was given by the user
hasha[:random_numbers].each do |num|
  if hash_totals[num]
    hash_totals[num][:random_freq] += 1
  else 
    hash_totals[num] = {:random_freq => 1, :user_freq => 0}
  end 
end 

hasha[:user_input].each do |num|
  if hash_totals[num]
    hash_totals[num][:user_freq] += 1
  else 
    hash_totals[num] = {:random_freq => 0, :user_freq => 1}
  end
end


#using only the first hash 
3.times do 
  puts "Thank you.  Please choose a number you want more information about:" 
newnum = gets.chomp.to_i
#Do the following two different ways: first only leveraging the information in the first hash, and then by only leveraging the information in the second hash.
# ask the user to supply 3 nums 
# share the # of times generated by computer
#share the # of times generated by user 
x = hasha[:random_numbers].count(newnum)

y = hasha[:user_input].count(newnum)

puts "The number #{newnum} was generated by the computer #{x} times, and was generated by the user #{y} times."
end
#using only the second hash 
3.times do 
  puts "Thank you. Please choose a number you want more information about:"
  newnum2 = gets.chomp.to_i
  if hash_totals.include?(newnum2)
    xx = hash_totals.fetch(newnum2)[:random_freq]
    yy = hash_totals.fetch(newnum2)[:user_freq]
  else 
    xx = 0
    yy = 0
  end
  

puts "The number #{newnum2} was generated by the computer #{xx} times, and was generated by the user #{yy} times."
end
